DEBUG 2019-04-21 03:39:31,337: 	 Executing command: 'getlog'
DEBUG 2019-04-21 03:39:31,337: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
ERROR 2019-04-21 03:39:31,338: 	 Error: crab_Run2018A/crab_Bparking_Run2018Als is not a valid CRAB project directory.
ERROR 2019-04-21 03:39:31,338: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 268, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 586, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_Run2018A/crab_Bparking_Run2018Als is not a valid CRAB project directory.
DEBUG 2019-04-24 17:10:09,796: 	 Executing command: 'resubmit'
DEBUG 2019-04-24 17:10:09,796: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
DEBUG 2019-05-13 06:52:10,733: 	 Executing command: 'submit'
DEBUG 2019-05-13 06:52:10,735: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
DEBUG 2019-05-13 06:52:10,799: 	 Checking credentials
DEBUG 2019-05-13 06:52:10,801: 	 Found proxy file /tmp/x509up_u112971
DEBUG 2019-05-13 06:52:10,801: 	 Getting proxy life time left
DEBUG 2019-05-13 06:52:12,008: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112971 -timeleft
 output : 43142

 error: 
 retcode : 0
DEBUG 2019-05-13 06:52:12,814: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112971 -actimeleft
 output : 43141

 error: 
 retcode : 0
DEBUG 2019-05-13 06:52:12,815: 	 Proxy lifetime 43142 secs is different from voms extension lifetime 43141 secs for proxy: /tmp/x509up_u112971
DEBUG 2019-05-13 06:52:12,815: 	 Proxy valid for 11:59:01 hours
INFO 2019-05-13 06:52:12,815: 	 Will use CRAB configuration file dstard0_cfg.py
DEBUG 2019-05-13 06:52:12,815: 	 Loading CRAB configuration file.
ERROR 2019-05-13 06:52:19,339: 	 Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/dstard0_cfg.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-05-13 06:52:19,339: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/dstard0_cfg.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-05-13 07:02:49,413: 	 Executing command: 'submit'
DEBUG 2019-05-13 07:02:49,414: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
DEBUG 2019-05-13 07:02:49,436: 	 Checking credentials
DEBUG 2019-05-13 07:02:49,439: 	 Found proxy file /tmp/x509up_u112971
DEBUG 2019-05-13 07:02:49,439: 	 Getting proxy life time left
DEBUG 2019-05-13 07:02:50,547: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112971 -timeleft
 output : 43142

 error: 
 retcode : 0
DEBUG 2019-05-13 07:02:51,457: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112971 -actimeleft
 output : 43141

 error: 
 retcode : 0
DEBUG 2019-05-13 07:02:51,457: 	 Proxy lifetime 43142 secs is different from voms extension lifetime 43141 secs for proxy: /tmp/x509up_u112971
DEBUG 2019-05-13 07:02:51,457: 	 Proxy valid for 11:59:01 hours
INFO 2019-05-13 07:02:51,457: 	 Will use CRAB configuration file dstard0_cfg.py
DEBUG 2019-05-13 07:02:51,457: 	 Loading CRAB configuration file.
ERROR 2019-05-13 07:02:58,494: 	 Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/dstard0_cfg.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-05-13 07:02:58,494: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/dstard0_cfg.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-05-13 07:08:10,668: 	 Executing command: 'submit'
DEBUG 2019-05-13 07:08:10,668: 	 Found CRAB cache file /afs/cern.ch/user/r/ragomesd/.crab3
DEBUG 2019-05-13 07:08:10,687: 	 Checking credentials
DEBUG 2019-05-13 07:08:10,689: 	 Found proxy file /tmp/x509up_u112971
DEBUG 2019-05-13 07:08:10,689: 	 Getting proxy life time left
DEBUG 2019-05-13 07:08:11,599: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112971 -timeleft
 output : 42821

 error: 
 retcode : 0
DEBUG 2019-05-13 07:08:12,307: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u112971 -actimeleft
 output : 42820

 error: 
 retcode : 0
DEBUG 2019-05-13 07:08:12,307: 	 Proxy lifetime 42821 secs is different from voms extension lifetime 42820 secs for proxy: /tmp/x509up_u112971
DEBUG 2019-05-13 07:08:12,307: 	 Proxy valid for 11:53:40 hours
INFO 2019-05-13 07:08:12,307: 	 Will use CRAB configuration file crab_Bparking_Run2018A_config.py
DEBUG 2019-05-13 07:08:12,307: 	 Loading CRAB configuration file.
DEBUG 2019-05-13 07:08:12,310: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-05-13 07:08:12,310: 	 Working area '/afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_Run2018A/crab_Bparking_Run2018A' already exists 
Please change the requestName in the config file
ERROR 2019-05-13 07:08:12,310: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/r/ragomesd/B_parking/CMSSW_10_2_7/src/BanalysisMiniAOD-1/BAnalyzer/python/crab_Run2018A/crab_Bparking_Run2018A' already exists 
Please change the requestName in the config file
